---
title: "How to generate a cell means model and run linear combinations in R"
author: "Naren Srinivasan"
date: "5 December 2018"
output: html_document
---
 
# The problem **[Put on hold]**

\link{https://stackoverflow.com/questions/53625277/how-to-generate-a-cell-means-model-and-run-linear-combinations-in-r}


I came across this fantastic Stata tutorial here on interpreting interaction effects: https://stats.idre.ucla.edu/stata/faq/what-happens-if-you-omit-the-main-effect-in-a-regression-model-with-an-interaction/.

I have a situation where I have three experiments, each of which has three conditions, and I want to compare across conditions (testing, for example, Condition A of experiment A against Condition A of experiment B).

From the above link, it looks like the following in Stata is the right approach:

We can get a clearer picture of the cell means model by rerunning the analysis with the noconstant option and using ibn factor variable notation to suppress a reference group.

regress write ibn.female#ibn.grp, nocons

      Source |       SS       df       MS              Number of obs =     200
-------------+------------------------------           F(  8,   192) = 1058.74
       Model |    562175.3     8  70271.9125           Prob > F      =  0.0000
    Residual |  12743.7001   192  66.3734378           R-squared     =  0.9778
-------------+------------------------------           Adj R-squared =  0.9769
       Total |      574919   200    2874.595           Root MSE      =   8.147

------------------------------------------------------------------------------
       write |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
  female#grp |
        0 1  |   41.82609   1.698765    24.62   0.000     38.47545    45.17672
        0 2  |   49.14286   1.777819    27.64   0.000     45.63629    52.64942
        0 3  |   51.92857   1.539636    33.73   0.000      48.8918    54.96534
        0 4  |   58.57895   1.869048    31.34   0.000     54.89244    62.26545
        1 1  |   50.96296   1.567889    32.50   0.000     47.87046    54.05546
        1 2  |      53.25   1.662997    32.02   0.000     49.96991    56.53009
        1 3  |   57.34375   1.440198    39.82   0.000     54.50311    60.18439
        1 4  |   57.88462   1.597756    36.23   0.000     54.73321    61.03602
------------------------------------------------------------------------------

Followed by

`lincom 0.female#2.grp - 0.female#1.grp`

What is the R equivalent of "regress write ibn.female#ibn.grp, nocons" to generate cell means, and then subsequently test linear combinations of variables?

# The solution

```{r}
df <- data.frame(y = rnorm(n = 270),
                 comb = sample(paste0(c("e1, e2, e3"), c("c1", "c2", "c3"))))
```

